apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app:  hello-world
  type:  NodePort
  ports:
    - name:  http
      port:  80
      targetPort:  http
      protocol: TCP