- hosts: web
  remote_user: root
  become: yes
  tasks:
  - name: Update All Packages
    yum:
      name: '*'
      state: latest
  - name: Install Apache
    yum: 
      name: httpd
      state: installed
  - name: Create The HTML File
    shell: echo "Hello From The Ansible Challenge" > /var/www/html/index.html
    args:
      executable: /bin/bash
    notify:
      - Reload Apache
  - name: Show host IP 
    debug:
      msg: "{{ ansible_ssh_host }}"
  - name: FirewallD rules
    firewalld:
      zone: public
      service: http
      permanent: yes
      state: enabled
  - name: reload service firewalld
    systemd:
      name: firewalld
      state: reloaded
  # - name: Uninstall Apache
  #  yum: 
  #    name: httpd
  #    state: removed
  handlers:
    - name: Reload Apache
      service:
        name: httpd
        state: reloaded