- hosts: web
  remote_user: root
  become: yes
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: installed
  - name: Restart Apache
    service:
      name: httpd
      state: restarted
  - name: Remove Apache
    yum:
      name: httpd
      state: removed