all:
  hosts:
    mail.mycorp.local:
    smtp.mycorp.local:
    auth.mycorp.local:
  children:
    itlappsrv:
      children:
        ldnappsrv:
          hosts: 
            app01.ldn.mycorp.local:
            app02.lnd.mycorp.local:
        txappsrv:
          hosts:
            app03.tx.mycorp.local:
            app04.tx.mycorp.local:
    dc:
      children:
        dc01.mycorp.local
        dc02.mycorp.local