fruit:
  red:
    - strawberry
    - tomato
  orage:
    - orange
  yellow:
    - banana
  green:
    - grapes
    - watermelon
  total: 6

veg:
  yellow:
    - peppers
  orange:
    - carrot
  green:
    - broccoli
    - cabbage
    - lettuce
  total: 5