apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  ports:
    - port: {{ .Values.service.internalPort }}
      nodePort: {{ .Values.service.externallPort }}
  selector:
    app: nodejs
  type: {{ .Values.service.type }}
