---
  - hosts: web_portal
    tasks:
      - name: Apt get update
        apt: update_cache=yes

      - name: Install Apache2, nginx, nmap
        apt: name={{ item }} update_cache=no
        with_items:
          - apache2
          - nginx
          - nmap

      - name: Copy data files
        copy: src=index.html dest=/var/www/html/
        register: copy_status

      - name: Stop Apache2 service
        service: name=apache2 state=stopped

      - name: Copy template files
        template: src=current.html.j2 dest=/var/www/html/current.html
        notify:
          - start apache

      - name: Testing conditional
        shell: uptime
        when: ansible_hostname == "node1"

      - name: Testing until
        shell: service apache2 status
        register: result
        until: result.stdout.find("active (running)") != -1
        retries: 5
        delay: 5

      - name: Check uptime
        shell: uptime
        register: uptime_var

      - name: Print uptime
        debug: var=uptime_var

      - name: Copy status
        debug: var=copy_status

    handlers:
      - name: start apache
        service: name=apache2 state=restarted



