# Default values for nodejs-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: NULL
  tag: NULL

service:
  type: NodePort
  internalPort: 3000
  externallPort: 30333
