apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
    type: front-end
  name: my-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    type: front-end
  type: NodePort
